<section id="contact" class="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-md-5 pull-center">
                <h4>Kontakt</h4>
                <div>Frizer Mirko s.p.</div>
                <div>Davčna št.: 32432434</div>
                <div>Frizerska ulica 5,1000 Ljubljana</div>
                <div>Tel.: 01/34543546</div>
                <div>Email:frizer.mirko@f-mirko.com</div>
                <br>
            </div>
            <div class="col-md-2">
                <a class="thumbnail">
                    <img src="images/mh_logo_final_1.jpg" class="img-rounded" class="img-responsive" style="width:150px;height:150px">
                </a>
            </div>
            <div class="col-md-2 pull-right">
                <h4>Navigacija</h4>
                <li><a class="page-scroll" href="#services">Kaj nudimo</a></li>
                <li><a class="page-scroll" href="#contactUs">Naroči se</a></li>
                <li><a class="page-scroll" href="#faq">Pogosta vprašanja</a></li>
                <li><a href="#" data-toggle="modal" data-target="#myModal">O nas</a></li>
            </div>
        </div>
    </div>
</section>